### ISSUE TITLE
Groups do not re-generate after adding more players.

### ISSUE THREAD

**Issue by angelleye** [angelleye/table-tennis-league-app#14]
http://fiber.angelleye.com/temp/group-list-issue/group-list-issue.mp4

**Comment by keyurptl** [comment]
http://screencast.com/t/2sPf7vt6

**Comment by angelleye** [comment]
Names in the list on the left always pull fresh from the DB, so in my example I was adding names there were already on the right, which is why  it wasn't creating new groups.
