### ISSUE TITLE
Generate round-robin results sheets.

### ISSUE THREAD

**Issue by angelleye** [angelleye/table-tennis-league-app#15]
After our groups are created and we've made any necessary adjustments, we can generate our round-robin form.

Here is the PDF form we've been using.

[10-players.pdf](https://github.com/angelleye/table-tennis-league-app/files/543559/10-players.pdf)

This needs to be converted to an HTML table, one for each group, and we need to be able to easily access each different group's table.

The sample is for a 10 player group, but as you know we are starting with groups of 6.  After adjustments, some groups may have more than or few than 6, so our HTML table can simply display the number of rows it needs for the number of players it has in that group.

For example, in Adobe Acrobat I can easily switch between each open group sheet by clicking on the different tabs:

![image](https://cloud.githubusercontent.com/assets/629241/19587467/1aa7e14a-9724-11e6-94e0-5b6dbc39388e.png)

I'd like to replicate this functionality in our app. 

The names would be automatically filled out from the groups we created, of course, but then we also need the ability to easily add a new player to any given group at this point.  

This could be as simple as typing in their name directly on the results form.  We don't need go back to the list at this point. 

So above I mentioned we could create the same number of rows for the number of players, but maybe we simply leave one additional row empty at the bottom of each group so that you can quickly type in the name of a new player for that group if you need to.  If you do this, another empty row would be added below that in case you need to add more.

**Comment by angelleye** [comment]
Results are very important, so they should always be saved to the database so we don't lose data.  Any time content is updated in the form the db should be updated on the fly, and we should be able to reload results from any given day at any time.

We'll build that results history section later, but for now we just need to make sure the data is always in the db ready for us to pull when necessary.

**Comment by angelleye** [comment]
We also need to update the "Place" column on the results form along with the Match Record and Game Record.

The person with the best Match Record would be 1st place, then next best is 2nd place, etc.

If there is a tie with the Match Record, you then move to Game Record, and the person with the highest winning percentage based on their number of games would be the winner (or whatever place was next to be set.)

For example, if 3 people have a Match Record of 3-1, it might break down like this...

Player A | Game Record - 9-5 | Winning % - 64%
Player B | Game Record - 9-6 | Winning % - 60%
Player C | Game Record - 9-3 | Winning % - 75%

The order of placement would be Player C, Player A, Player B

**Comment by keyurptl** [comment]
@angelleye --> By mistake I done typo mistake at the time of commit, so now I have added link of commit in this comment, so please review below link for my commit on this Issue-15...

[Validation changed with BootstrapMaster dynamically with callback for every cell . changes in saveResult.php for duplicate records , changes in resultFroms.php for conditions goes wrong. ref #15](https://github.com/angelleye/table-tennis-league-app/commit/84798bf751c920c282b893d95f9aa11f5cffb39b)

**Comment by angelleye** [comment]
so is this issue fully ready for review now, or what?  I'm confused.  If it's ready please mark it ready for review in the labels.
