### ISSUE TITLE
Database design for results.

### ISSUE THREAD

**Issue by angelleye** [angelleye/table-tennis-league-app#20]
In #15 we're generating results history in the database, so that design needs to be well planned before being put into action.

Also, need to generate a new installer that we did in #6.

**Comment by keyurptl** [comment]
**For event**
`CREATE TABLE`event`(
`event_id`int(11) NOT NULL AUTO_INCREMENT,
`event_date`varchar(25) NOT NULL,
`group_list`text NOT NULL,
`player_list`text NOT NULL,
`total_players`int(11) NOT NULL,
`total_groups`int(11) NOT NULL,PRIMARY KEY (`event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;`

**For  Result** 

`CREATE TABLE`result_tt`(
`result_id`int(11) NOT NULL AUTO_INCREMENT,
`event_id`int(11) NOT NULL,
`winner_id`int(11) NOT NULL,
`looser_id`int(11) NOT NULL,
`winner_game_count`int(11) NOT NULL,
`looser_game_count`int(11) NOT NULL,
`game_record`varchar(255) NOT NULL,
`match_record`varchar(255) NOT NULL,
`place`varchar(255) NOT NULL,PRIMARY KEY (`result_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;`

**Comment by angelleye** [comment]
I'm going to have a hard time seeing this as create statements.

Please go ahead and create the data as you see fit, and then open up the relationships window in whatever db tool you're using so I can see the tables, fields, and relationships that way.
