### ISSUE TITLE
Drag and drop doesn't work on mobile device..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/table-tennis-league-app#21]
I was testing the app from an Android tablet and everything works great except for the drag and drop.

Bootstrap elements are supposed to work on mobile devices, right?  Same with jQuery or whatever we used for the drag and drop stuff..??

Need to get that working.  That was one of the primary features we'd be using (moving names around after groups are auto-generated)

**Comment by keyurptl** [comment]
Added that Js file in issue  #15
