### ISSUE TITLE
Settings - Roster File URL

### ISSUE THREAD

**Issue by angelleye** [angelleye/table-tennis-league-app#23]
In #16 we added a settings panel.  Here we will be adding an additional option into the settings / app.

Right now, the player roster is manually uploaded via a CSV file.  This is necessary because the roster file is behind a login protected URL hosted by a 3rd party.  

I would like to add this option into our settings:  Roster File URL

If this setting has a value, then we'll add an additional option to the home screen where we have the file upload happening now.  We can add a button that says "Pull Roster from Website".

If this button is pushed, the roster would be loaded from that URL instead of a file upload.

This will allow me to simply pull the roster and put it somewhere on my own webserver that isn't protected like the 3rd party source is, and this will make it easier on users so they don't have to mess with download a CSV and uploading it manually.

**Comment by angelleye** [comment]
For example, I could fill in this URL:  www.kansascitytabletennis.com/_assets/roster.csv

That would make the extra button show up to "Pull Roster from Website", but I could still upload manually if I want to.

**Comment by keyurptl** [comment]
By mistake i forgot to add ref #23 while commiting, so added that in comment.

[Chnages in settings.php as per requirements and added validation and new file as insertFromRoster.php to read data from url and save in database, ref #23](https://github.com/angelleye/table-tennis-league-app/commit/dfb02e1076526b335e9ee281a87cfd86c879e971)
