### ISSUE TITLE
Submit & Email All Results Bug

### ISSUE THREAD

**Issue by angelleye** [angelleye/table-tennis-league-app#32]
I created some groups and I only filled out a portion of the first group's results.  Then I went ahead and clicked the Submit & Email All Results button.

It showed the "Loading" graphic and got stick on that.  It wouldn't move forward.

I checked with Chrome Console and nothing shows up there at all when I push the button.  

If I refresh the page, the loader graphic still displays, but then I can push the "stop" button in the browser and it will put me back to where I was on the group table.

**Comment by angelleye** [comment]
I was thinking maybe this happened because I needed to do a fresh install, but I've done that, and it's still happening.  I cannot get the results to submit / email.

**Comment by keyurptl** [comment]
@angelleye  , 
i have run in your link For this issue
check this link [http://www.screencast.com/t/ThjXEqItE](http://www.screencast.com/t/ThjXEqItE) 
Its SMTP issue from server side. also see it tooks 2.2 min for processing, i dont know why but it shows here faster than that.

**Comment by angelleye** [comment]
So what SMTP credentials are you using?

That server sends mail from every other app/platform on it without issue.

**Comment by keyurptl** [comment]
```
$mail->Host = 'smtp.gmail.com';
$mail->SMTPAuth = true;   
$mail->SMTPSecure = 'ssl';  
$mail->Port = 465;     
```

and my username & password of mail.

**Comment by angelleye** [comment]
Why are you using a 3rd party SMTP server instead of just letting PHP mail handle it?  PHPMailer handles that just fine.

**Comment by angelleye** [comment]
Something real simple like this:  https://github.com/PHPMailer/PHPMailer/blob/master/examples/mail.phps

**Comment by keyurptl** [comment]
Okay i understand, i will amend it.
