### ISSUE TITLE
Settings page missing menu items..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/table-tennis-league-app#40]
The settings page does not have any menu items in the menu bar.

![image](https://cloud.githubusercontent.com/assets/629241/20472346/9ccce004-af7e-11e6-9081-784c7bb640d9.png)

I hope you don't have the menu separate on every page..??  We should have a common header getting used on all pages.

**Comment by keyurptl** [comment]
Currently we have separated menu on every page because we cant add / view users from setting, history,resultForm so that i have added common menu in 2 pages that are eventHistory.php and settings.php
