### ISSUE TITLE
History Date Bug..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/table-tennis-league-app#41]
When I first did a history search it worked just fine.  For some reason it is now broken.  Somehow the validation is broken and it's not letting me submit even though I have a date entered.

![image](https://cloud.githubusercontent.com/assets/629241/20472379/ee754f22-af7e-11e6-97a7-26d4ae623107.png)

Refreshing the page seemed to fix it, but this will confuse users.  Need to make sure that doesn't happen.

**Comment by keyurptl** [comment]
@angelleye  This works perfect here, You can check this link

[http://www.screencast.com/t/Pr4CCM7m](http://www.screencast.com/t/Pr4CCM7m)
