### ISSUE TITLE
Lists are not sorting.

### ISSUE THREAD

**Issue by angelleye** [angelleye/table-tennis-league-app#8]
The lists page is still not sorting by rating.  We need both left and right side to sort by rating, highest to lowest.

So I could drag a name and drop it anywhere, and it would automatically re-sort accordingly.

**Comment by keyurptl** [comment]
i have done this task with issue no. 9

**Comment by angelleye** [comment]
Curious why that is?  These two issues aren't related, so why were they done together in the same issue instead of separate?
